# Generated by Django 5.2.3 on 2025-06-17 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0003_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='entry_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='worker',
            name='entry_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='worker',
            name='father_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='identification_marks',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='worker',
            name='pass_pdf',
            field=models.FileField(blank=True, null=True, upload_to='entry_passes/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='police_station',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='purpose',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
