# Generated by Django 5.2.3 on 2025-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0004_worker_address_worker_age_worker_entry_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='designation',
            field=models.CharField(default='N/A', max_length=40),
        ),
        migrations.AddField(
            model_name='worker',
            name='mob_no',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
